### ISSUE TITLE
May I kindly know how should user to access the drug related datasets drug_target_gdsc.rds.gz, drug_target_ctrp.rds.gz ? 

### ISSUE THREAD

**Issue by TINGJINJANE** [GuoBioinfoLab/GSCALite#3]
In any chance, these drug-related datasets could be accessed by the users for further analysis.

**Comment by chunjie-sam-liu** [comment]
Hi @TINGJINJANE ,
The drug datasets in the GSCALite are downloaded from GDSC and CTRP drug database. You can download raw data  from the website or I share our processed data to you.

**Comment by TINGJINJANE** [comment]
May I have your processed data?  

I read your paper, it mentioned that you used the method in Rees et al, 2016 to calculate the Spearman correlation analysis with the small molecule/drug sensitivity (IC50). Then I read the drug-related code;  I did not find how your processing the data. I am really interested in the drug part of your website. 

May I kindly know if I could have your processed data for further analysis? Thanks so much for your help and time.

**Comment by chunjie-sam-liu** [comment]
@TINGJINJANE 
You can download the processed data from the [link](https://drive.google.com/drive/folders/1mm_slgBeavOBTPg57tuslkNyf9KSBoaV?usp=sharing). Please cite our work if you do further analysis based on the processed data.😀

My suggestion is that the datasets in drug databases are updated. Even though they added few small molecules, you may download raw data in your work. The update of GSCALite shall include more cell lines and drugs in our future work.

**Comment by TINGJINJANE** [comment]
Thanks, Sam, I have downloaded the datasets. BTW,  I appreciate your suggestion. Definitely, I will cite your awesome work.
